CREATE TABLE oauth_authorization_codes
(
    id          UUID                        NOT NULL,
    project_id  UUID                        NOT NULL,
    user_id     UUID                        NOT NULL,
    code        VARCHAR(255)                NOT NULL,
    scope       VARCHAR(255)                NOT NULL,
    redirectUri VARCHAR(255)                NOT NULL,
    state       VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expires_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_oauth_authorization_codes PRIMARY KEY (id)
);

CREATE TABLE oauth_consent_records
(
    id         UUID                        NOT NULL,
    owner_id   UUID                        NOT NULL,
    project_id UUID                        NOT NULL,
    createdAt  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expiresAt  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_oauth_consent_records PRIMARY KEY (id)
);

CREATE TABLE oauth_requests
(
    id           UUID                        NOT NULL,
    client_id    VARCHAR(255)                NOT NULL,
    redirect_uri VARCHAR(255)                NOT NULL,
    scope        VARCHAR(255)                NOT NULL,
    state        VARCHAR(255),
    project_id   UUID                        NOT NULL,
    createdAt    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expiresAt    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_oauth_requests PRIMARY KEY (id)
);

CREATE TABLE oauth_tokens
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id               UUID                                    NOT NULL,
    user_id                  UUID                                    NOT NULL,
    scope                    VARCHAR(255),
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    access_token             VARCHAR(2048),
    refresh_token            VARCHAR(2048),
    access_token_expires_at  TIMESTAMP WITHOUT TIME ZONE,
    refresh_token_expires_at TIMESTAMP WITHOUT TIME ZONE,
    is_revoked               BOOLEAN,
    CONSTRAINT pk_oauth_tokens PRIMARY KEY (id)
);

CREATE TABLE project_redirect_uris
(
    project_id   UUID         NOT NULL,
    redirect_uri VARCHAR(255) NOT NULL
);

CREATE TABLE projects
(
    id            UUID                        NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    imageBlob     VARCHAR(255),
    client_secret VARCHAR(255)                NOT NULL,
    owner_id      UUID                        NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       UUID         NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email    VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    user_id UUID NOT NULL,
    role    VARCHAR(255)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE oauth_authorization_codes
    ADD CONSTRAINT FK_OAUTH_AUTHORIZATION_CODES_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE oauth_authorization_codes
    ADD CONSTRAINT FK_OAUTH_AUTHORIZATION_CODES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE oauth_consent_records
    ADD CONSTRAINT FK_OAUTH_CONSENT_RECORDS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE oauth_consent_records
    ADD CONSTRAINT FK_OAUTH_CONSENT_RECORDS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE oauth_requests
    ADD CONSTRAINT FK_OAUTH_REQUESTS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE oauth_tokens
    ADD CONSTRAINT FK_OAUTH_TOKENS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE oauth_tokens
    ADD CONSTRAINT FK_OAUTH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE project_redirect_uris
    ADD CONSTRAINT fk_project_redirect_uris_on_project FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_users_roles_on_user FOREIGN KEY (user_id) REFERENCES users (id);