quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
quarkus.datasource.jdbc.max-size=16

quarkus.native.additional-build-args=--features=org.graalvm.nativeimage.feature.java.awt.JavaAWTFeature,--add-exports=java.desktop/sun.awt=ALL-UNNAMED,--add-exports=java.desktop/sun.font=ALL-UNNAMED

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${CORS_ORIGINS}
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.methods=GET, PUT, POST, DELETE, OPTIONS
quarkus.http.cors.access-control-allow-credentials=true

quarkus.flyway.migrate-at-start=true

aren.use_https=${USE_HTTPS}
aren.cookie-domain=${COOKIE_DOMAIN}

aren.frontend.url=${FRONTEND_URL}

aren.jwt.issuer=${JWT_ISSUER}
mp.jwt.verify.issuer=${aren.jwt.issuer}

aren.upload-dir=${UPLOAD_DIR}
# 5MB
aren.max-upload-size=5242880
# Max form upload size, including all form attributes. This is needed to allow uploading files larger than 5MB, as the default max form attribute size is 2MB.
quarkus.http.limits.max-form-attribute-size=20M
